---
# tasks file for disableWINSReg
- name: Disable {{ attribute_name }}
  community.general.ilo_redfish_config:
    category: "Manager"
    command: "SetWINSReg"
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
    attribute_name: "{{ _attribute_name_ }}"

