---
- name: Get SNMP alert destinations
  ilo_snmp:
    category: "Manager"
    command: "GetSNMPAlertDestinations"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result

- name: SNMP alert destinations in the server
  debug:
    msg: "{{ result }}"

