---
- name: Get SNMP alert destinations
  register: result
  hpe.ilo.ilo_snmp:
    category: Manager
    command: GetSNMPAlertDestinations
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"

- name: SNMP alert destinations in the server
  ansible.builtin.debug:
    msg: "{{ result }}"

