---
# tasks file for get_manager_inventory
- name: Get Manager Inventory
  community.general.redfish_info:
    category: "Manager"
    command: "GetManagerInventory"
    baseuri: "{{ _baseuri_ }}"
    # username: "{{ username }}"
    # password: "{{ password }}"
    auth_token: "{{ _auth_token_ }}"
  register: result_attr

