---
# tasks file for getnicinven
- name: Get NIC Information
  community.general.redfish_info:
    category: "Systems"
    command: "GetNicInventory"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result_attr

