---
- name: Get SNMPv3 users
  ilo_snmp:
    category: "Manager"
    command: "GetSNMPv3Users"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result

- name: SNMPv3 users in the server
  debug:
    msg: "{{ result }}"

