---
- name: Get firmware upgrade/upload status
  ilo_firmware:
    category: "TaskService"
    command: "GetFirmwareStatus"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result

- name: Status
  debug:
    msg: "{{ result }}"

