---
# tasks file for getcpuinven
- name: Get CPU Inventory
  community.general.redfish_info:
    category: "Systems"
    command: "GetCpuInventory"
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
  register: result_attr

