---
- name: Get USB information
  register: usb_info
  hpe.ilo.ilo_storage:
    category: Systems
    command: GetUSBInfo
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"

- name: USB information in the server
  ansible.builtin.debug:
    msg: "{{ usb_info }}"

