---
- name: Get logical drives details with array controllers
  register: logical_drives_data
  hpe.ilo.ilo_storage:
    category: Systems
    command: GetLogicalDrivesWithArrayControllers
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"

- name: Logical drives present in the server
  ansible.builtin.debug:
    msg: "{{ logical_drives_data }}"

