---
# tasks file for updateusername
- name: Update user name
  community.general.redfish_command:
    category: "Accounts"
    command: "UpdateUserName"
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
    account_username: "{{ _account_username_ }}"
    account_updatename: "{{ _account_updatename_ }}"

