---
- hosts: myhosts
  connection: local
  name: Bios Update service
  gather_facts: false

  tasks:
    - name: Flashfwpkg
      hpe.ilo.ilo_fwupdate_command:
        category: UpdateService
        command: Flashfwpkg
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        fwpkg_file: U32_2.76_11_17_2022.fwpkg
