---
- hosts: myhosts
  connection: local
  name: Upload iLO5 component
  gather_facts: False

  tasks:
    - name: Upload component
      hpe.ilo.ilo_fwupdate_command:
        category: "UpdateService"
        command: "UploadComponent"
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        fwpkg_file: "ilo5_272.fwpkg"

