---
# tasks file for getmeminven
- name: Get memory inventory
  community.general.redfish_info:
    category: "Systems"
    command: "GetMemoryInventory"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result_attr

