---
# tasks file for getmeminven
- name: Get memory inventory
  community.general.redfish_info:
    category: "Systems"
    command: "GetMemoryInventory"
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
  register: result_attr

