---
- name: Get logical drives
  ilo_storage:
    category: "Systems"
    command: "GetLogicalDrives"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: logical_drives_data

- name: Logical drives present in the server
  debug:
    msg: "{{ logical_drives_data }}"

