---
- name: Get server PostState
  register: server_poststate
  hpe.ilo.ilo_power:
    category: "Systems"
    command: "GetServerPostState"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"

- name: Server PostState
  ansible.builtin.debug:
    msg: "{{ server_poststate }}"

