---
- name: Verify BIOS attributes when username and password are defined
  community.general.redfish_command:
    category: "Systems"
    command: "VerifyBiosAttributes"
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
    bios_attributes: "{{ _bios_attributes_ }}"
  register: result

- name: Status
  ansible.builtin.debug:
    msg: "{{ result }}"

