---
- name: Verify BIOS attributes when username and password are defined
  community.general.redfish_command:
    category: Systems
    command: VerifyBiosAttributes
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
    bios_attributes: "{{ bios_attributes }}"
  register: result

- name: Status
  ansible.builtin.debug:
    msg: "{{ result }}"
