---
# tasks file for getfirmupdate
- name: Get Firmware Update Capabilities
  community.general.redfish_info:
    category: "Update"
    command: "GetFirmwareUpdateCapabilities"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result_attr

