---
- hosts: myhosts
  connection: local
  name: Install Smart Component
  gather_facts: False

  tasks:
    - name: Install Smart Component
      hpe.ilo.ilo_fwupdate_command:
        category: "RLCP"
        command: "SmtCmpInstall"
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"

