---
- hosts: myhosts
  connection: local
  name: Install Smart Component
  gather_facts: false

  tasks:
    - name: Install Smart Component
      ilo_fwupdate_command:
        category: RLCP
        command: SmtCmpInstall
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
