---
- hosts: myhosts
  connection: local
  name: Get Manager Logs
  gather_facts: False
  # vars_files: iLO_redfish.yml

  vars:
    datatype: Logs

  tasks:

  - name: Create session
    community.general.redfish_command:
      category: "Sessions"
      command: "CreateSession"
      baseuri: "{{ _baseuri_ }}"
      username: "{{ _username_ }}"
      password: "{{ _password_ }}"
    register: result

  - name: Define output file
    ansible.builtin.include_tasks: create_output_file.yml

  - name: Get Manager Logs
    community.general.redfish_info:
      category: "Manager"
      command: "GetLogs"
      baseuri: "{{ _baseuri_ }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
      auth_token: "{{ result.session.token }}"
    register: result_logs

  - name: Copy results to output file
    ansible.builtin.copy:
      content: "{{ result_logs | to_nice_json }}"
      dest: "{{ template }}.json"

  - name: Delete session using security token created by CreateSesssion above
    community.general.redfish_command:
      category: "Sessions"
      command: "DeleteSession"
      baseuri: "{{ _baseuri_ }}"
      auth_token: "{{ result.session.token }}"
      session_uri: "{{ result.session.uri }}"

