---
- hosts: myhosts
  connection: local
  name: Restart Manager
  gather_facts: False
  # vars_files: iLO_redfish.yml

  tasks:
  - name: Create session
    community.general.redfish_command:
      category: "Sessions"
      command: "CreateSession"
      baseuri: "{{ _baseuri_ }}"
      username: "{{ _username_ }}"
      password: "{{ _password_ }}"
    register: result

  - name: Restart Manager gracefully
    community.general.redfish_command:
      category: "Manager"
      command: "GracefulRestart"
      baseuri: "{{ _baseuri_ }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
      auth_token: "{{ result.session.token }}"

  - name: Delete session using security token created by CreateSesssion above
    community.general.redfish_command:
      category: "Sessions"
      command: "DeleteSession"
      baseuri: "{{ _baseuri_ }}"
      auth_token: "{{ result.session.token }}"
      session_uri: "{{ result.session.uri }}"

