---
- hosts: myhosts
  connection: local
  name: Set Manager DNS
  gather_facts: False
  # vars_files: iLO_redfish.yml

  vars:
    - dns_server: 1.1.1.1 2.2.2.2
    - domain_name: tst.sgp.hp.mfg

  tasks:
    - name: Create session
      community.general.redfish_command:
        category: "Sessions"
        command: "CreateSession"
        baseuri: "{{ _baseuri_ }}"
        username: "{{ _username_ }}"
        password: "{{ _password_ }}"
      register: result

    - name: Set DNS Server to {{ dns_server }}
      community.general.ilo_redfish_config:
        category: "Manager"
        command: "SetDNSserver"
        baseuri: "{{ _baseuri_ }}"
            # username: "{{ username }}"
            # password: "{{ password }}"
        attribute_name: "DNSServers"
        attribute_value: "{{ _attribute_value_ }}"
        auth_token: "{{ result.session.token }}"

    - name: Set Domain name to {{ domain_name }}
      community.general.ilo_redfish_config:
        category: "Manager"
        command: "SetDomainName"
        baseuri: "{{ _baseuri_ }}"
            # username: "{{ username }}"
            # password: "{{ password }}"
        attribute_name: "DomainName"
        attribute_value: "{{ _attribute_value_ }}"
        auth_token: "{{ result.session.token }}"

    - name: Delete session using security token created by CreateSesssion above
      community.general.redfish_command:
        category: "Sessions"
        command: "DeleteSession"
        baseuri: "{{ _baseuri_ }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"

