---
- hosts: myhosts
  connection: local
  gather_facts: False
  tasks:
  - name: Get service BIOS attributes
    get_service_bios_attributes:
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Service BIOS settings in the server
    debug:
      msg: "{{ result }}"

