---
- hosts: myhosts
  connection: local
  name: Get BIOS boot order
  gather_facts: false
  # vars_files: iLO_redfish.yml

  vars:
    datatype: BiosBootOrder

  tasks:
    - name: Define output file
      ansible.builtin.include_tasks: create_output_file.yml

    - name: Create session
      community.general.redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result

    - name: Get device boot order
      community.general.redfish_info:
        category: Systems
        command: GetBootOrder
        baseuri: "{{ baseuri }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
        auth_token: "{{ result.session.token }}"
      register: result_boot

    - name: Copy results to output file
      ansible.builtin.copy:
        content: "{{ result_boot | to_nice_json }}"
        dest: "{{ template }}.json"

    - name: Delete session using security token created by CreateSesssion above
      community.general.redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
