---
- name: Wait for iLO Reboot Completion
  register: result
  hpe.ilo.ilo_manage:
    category: "Systems"
    command: "WaitforiLORebootCompletion"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"

- name: iLO reboot status
  ansible.builtin.debug:
    msg: "{{ result }}"

