---
# tasks file for UpdateRole
- name: Update user role
  hpe.ilo.ilo_redfish_command:
    category: Accounts
    command: UpdateiLOUserRole
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
    loginname: "{{ loginname }}"
    roleid: "{{ roleid }}"
