---
- name: Perform firmware upload to ilo repository
  register: result
  hpe.ilo.ilo_firmware:
    category: UpdateService
    command: FirmwareUpload
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
    image_uri: "{{ image_uri }}"
    file_name: "{{ file_name }}"

- name: Status
  ansible.builtin.debug:
    msg: "{{ result }}"
