---
# tasks file for getiellogs
- name: Get Manager Logs
  community.general.redfish_info:
    category: "Manager"
    command: "GetLogs"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result_attr

