---
# tasks file for getchasspower
- name: Get chassis power
  community.general.redfish_info:
    category: "Chassis"
    command: "GetChassisPower"
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
  register: result_attr

