---
- name: Get network boot settings
  ilo_boot:
    category: "Systems"
    command: "GetBootSettings"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: network_boot_settings

- name: Boot settings present in the server
  debug:
    msg: "{{ network_boot_settings }}"

