---
- name: Erase Physical Drives
  ilo_storage:
    category: "Systems"
    command: "ErasePhysicalDrives"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result

- name: Status
  debug:
    msg: "{{ result }}"

