---
# tasks file for getfaninven
- name: Get fans statistics
  community.general.redfish_info:
    category: "Chassis"
    command: "GetFanInventory"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result_attr

