---
# tasks file for getfaninven
- name: Get fans statistics
  community.general.redfish_info:
    category: "Chassis"
    command: "GetFanInventory"
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
  register: result_attr

