---
- name: Perform restore operation on the iLO
  ilo_manage:
    category: "Manager"
    command: "iLORestore"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result

- name: Status
  debug:
    msg: "{{ result }}"

