---
- name: Delete all logical drives
  ilo_storage:
    category: "Systems"
    command: "DeleteAllLogicalDrives"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result

- name: Status
  debug:
    msg: "{{ result }}"

