---
# tasks file for deluser
- name: Delete user
  community.general.redfish_command:
    category: "Accounts"
    command: "DeleteUser"
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
    account_username: "{{ _account_username_ }}"

