---
- name: Enable Certificate Login
  register: result
  hpe.ilo.ilo_security:
    category: Manager
    command: EnableCertificateLogin
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"

- name: Status
  ansible.builtin.debug:
    msg: "{{ result }}"
