---
# tasks file for setDNS
- name: Set DNS Server to {{ dns_server }}
  community.general.ilo_redfish_config:
    category: "Manager"
    command: "SetDNSserver"
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
    attribute_name: "DNSServers"
    attribute_value: "{{ _attribute_value_ }}"

