---
# tasks file for listAllusers
- name: List all users
  register: result_attr
  hpe.ilo.ilo_redfish_info:
    category: Accounts
    command: ListiLOUsers
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
