---
# tasks file for getdefsysinv
- name: Get Inventory
  community.general.redfish_info:
    category: "Systems"
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
  register: result_attr

