---
# tasks file for getdefsysinv
- name: Get Inventory
  community.general.redfish_info:
    category: Systems
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result_attr

