---
# tasks file for getchassistherm
- name: Get chassis thermals
  community.general.redfish_info:
    category: "Chassis"
    command: "GetChassisThermals"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result_attr

