---
- name: Deleting all SNMP Alert Destinations
  register: result
  hpe.ilo.ilo_snmp:
    category: Manager
    command: DeleteAllSNMPAlertDestinations
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"

- name: Status
  ansible.builtin.debug:
    msg: "{{ result }}"
