---
- name: Verify logical drives
  ilo_storage:
    category: "Systems"
    command: "VerifyLogicalDrives"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
    raid_details: "{{ raid_details }}"
  register: result

- name: Logical drives verification status
  debug:
    msg: "{{ result }}"

