---
# tasks file for ledoff
- name: Turn LED off
  community.general.redfish_command:
    category: Chassis
    command: IndicatorLedOff
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
