---
- name: Get specified logical drives details
  ilo_storage:
    category: "Systems"
    command: "GetSpecifiedLogicalDrives"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
    logical_drives_names: "{{ logical_drives_names }}"
  register: logical_drives_data

- name: Logical drives present in the server
  debug:
    msg: "{{ logical_drives_data }}"

