---
- name: Get server Hostname
  ilo_manage:
    category: "Manager"
    command: "GetHostName"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: server_hostname

- name: Server Hostname
  debug:
    msg: "{{ server_hostname }}"

