---
# tasks file for getpsuinven
- name: Get PSU Inventory
  community.general.redfish_info:
    category: Chassis
    command: GetPsuInventory
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result_attr

