---
# tasks file for getpsuinven
- name: Get PSU Inventory
  community.general.redfish_info:
    category: "Chassis"
    command: "GetPsuInventory"
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
  register: result_attr

