---
# tasks file for iLOreset
- name: Restart Manager gracefully
  community.general.redfish_command:
    category: Manager
    command: GracefulRestart
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"

