---
- hosts: myhosts
  connection: local
  name: Update service UBM4
  gather_facts: False

  tasks:
    - name: Flashfwpkg
      hpe.ilo.ilo_fwupdate_command:
        category: UpdateService
        command: Flashfwpkg
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        fwpkg_file: HPE_UBM4_1.24_D.fwpkg

