---
- name: Enable Secure Boot
  community.general.redfish_config:
    category: Systems
    command: EnableSecureBoot
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result

- name: Status
  ansible.builtin.debug:
    msg: "{{ result }}"

