---
- name: Enable Secure Boot
  community.general.redfish_config:
    category: "Systems"
    command: "EnableSecureBoot"
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
  register: result

- name: Status
  ansible.builtin.debug:
    msg: "{{ result }}"

