---
- name: Get Drive Operating Mode
  ilo_storage:
    category: "Systems"
    command: "GetDriveOperatingMode"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result

- name: Drive Operating Mode
  debug:
    msg: "{{ result }}"

