---
- hosts: myhosts
  connection: local
  name: Add User
  gather_facts: False
  # vars_files: iLO_redfish.yml

  vars:
    - new_user: Bhavya_check2
    - new_pass: testpass
    - role_id: Administrator

  tasks:
    - name: Create session
      community.general.redfish_command:
        category: "Sessions"
        command: "CreateSession"
        baseuri: "{{ _baseuri_ }}"
        username: "{{ _username_ }}"
        password: "{{ _password_ }}"
      register: result

    - name: Add user
      community.general.redfish_command:
        category: "Accounts"
        command: "AddUser"
        baseuri: "{{ _baseuri_ }}"
           #  username: "{{ username }}"
           #  password: "{{ password }}"
        new_username: "{{ _new_username_ }}"
        new_password: "{{ _new_password_ }}"
        roleid: "{{ _roleid_ }}"
        auth_token: "{{ result.session.token }}"

    - name: Delete session using security token created by CreateSesssion above
      community.general.redfish_command:
        category: "Sessions"
        command: "DeleteSession"
        baseuri: "{{ _baseuri_ }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"

