---
- hosts: myhosts
  connection: local
  name: Update user password
  gather_facts: False
  # vars_files: iLO_redfish.yml

  vars:
  - account_username: Bhavya_check1
  - account_updatename: Bhav

  tasks:
    - name: Create session
      community.general.redfish_command:
        category: "Sessions"
        command: "CreateSession"
        baseuri: "{{ _baseuri_ }}"
        username: "{{ _username_ }}"
        password: "{{ _password_ }}"
      register: result

    - name: Update user name
      community.general.redfish_command:
        category: "Accounts"
        command: "UpdateUserName"
        baseuri: "{{ _baseuri_ }}"
            # username: "{{ username }}"
            # password: "{{ password }}"
        account_username: "{{ _account_username_ }}"
        account_updatename: "{{ _account_updatename_ }}"
        auth_token: "{{ result.session.token }}"

    - name: Delete session using security token created by CreateSesssion above
      community.general.redfish_command:
        category: "Sessions"
        command: "DeleteSession"
        baseuri: "{{ _baseuri_ }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"

