---
- hosts: myhosts
  connection: local
  name: Device Software Inventory
  gather_facts: False
  # vars_files: iLO_redfish.yml

  vars:
    datatype: SoftwareInventory

  tasks:
    - name: Create session
      community.general.redfish_command:
        category: "Sessions"
        command: "CreateSession"
        baseuri: "{{ _baseuri_ }}"
        username: "{{ _username_ }}"
        password: "{{ _password_ }}"
      register: result

    - name: Set output file
      ansible.builtin.include_tasks: create_output_file.yml

    - name: Get Software Inventory
      community.general.redfish_info:
        category: "Update"
        command: "GetSoftwareInventory"
        baseuri: "{{ _baseuri_ }}"
            # username: "{{ username }}"
            # password: "{{ password }}"
        auth_token: "{{ result.session.token }}"
      register: result_fw

    - name: Copy results to output file
      ansible.builtin.copy:
        content: "{{ result_fw | to_nice_json }}"
        dest: "{{ template }}.json"

    - name: Delete session using security token created by CreateSesssion above
      community.general.redfish_command:
        category: "Sessions"
        command: "DeleteSession"
        baseuri: "{{ _baseuri_ }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"

