---
# tasks file for setonetimeboot
- name: Set one-time boot device to {{ bootdevice }}
  community.general.redfish_command:
    category: "Systems"
    command: "SetOneTimeBoot"
    bootdevice: "{{ _bootdevice_ }}"
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
  register: bios_attribute
  # notify:
  #   - Reboot system to apply new BIOS settings

