---
- name: Get Device Inventory Information
  register: device_inventory_info
  hpe.ilo.ilo_device:
    category: Chassis
    command: GetDeviceInventoryInfo
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"

- name: Device Inventory Information in the server
  ansible.builtin.debug:
    msg: "{{ device_inventory_info }}"
