---
- name: Get Device Inventory Information
  ilo_device:
    category: "Chassis"
    command: "GetDeviceInventoryInfo"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: device_inventory_info

- name: Device Inventory Information in the server
  debug:
    msg: "{{ device_inventory_info }}"

