---
# tasks file for rlcpinstall
- name: Copy file to remote machine
  ansible.builtin.expect:
    command: "{{ _command_ }}"
    responses:
      .*password.*: '{{ password }}'
      .*Are you sure you want to continue connecting.*: "yes\n"
    echo: true
  register: scp_output

- name: Install Package
  hpe.ilo.ilo_fwupdate_command:
    category: "RLCP"
    command: "PackageInstall"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
    remote: "{{ remote_file_path }}"
    install_filename: "{{ filename }}"

