---
# tasks file for getDiskinven
- name: Get disk inventory
  community.general.redfish_info:
    category: "Systems"
    command: "GetDiskInventory"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result_attr

