---
# tasks file for getDiskinven
- name: Get disk inventory
  community.general.redfish_info:
    category: "Systems"
    command: "GetDiskInventory"
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
  register: result_attr

