---
# tasks file for get_health_report
- name: Get Health Report
  community.general.redfish_info:
    category: "Manager"
    command: "GetHealthReport"
    baseuri: "{{ _baseuri_ }}"
    # username: "{{ username }}"
    # password: "{{ password }}"
    auth_token: "{{ _auth_token_ }}"
  register: result_attr

